tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'TXOJWBL-RJ39239'
      user: 'JJOV'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: dev
      warehouse: tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: 'TXOJWBL-RJ39239'
      user: 'JJOV'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: tasty_bytes_dbt_wh